import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import { useRouter } from 'next/router';
import { Console } from 'console';
import { features } from 'process';
import StrapiClient from '../lib/strapi-client';
import { useEffect, useState } from "react";
import axios from "axios"; 

export default function Index(data){
  // useEffect(()=>{
  //   const vimal =async () => {
  //     const data=await axios.get("http://localhost:1337/api/index");
  //     console.log(data)
  //   };
  //   vimal();
  // },[]);
    // console.log(data.getstarted.data.attribute)
    console.log(data.data.attributes.Title)
    console.log(data.data.attributes.Description) 
    // console.log(data,feature.data.attributes.title)
  return (
    <div className={styles.container}>
      <Head>
        <title>data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="w-full-screen pl-4 bg-gray-900">
    <div className="flex flex-col flex-wrap items-center justify-between h-12 mx-auto md:flex-row max-w-full">
      <a
        href="#_"
        className="flex items-center order-first h-12 font-medium text-gray-900 lg:order-none lg:w-auto title-font lg:items-center lg:justify-center md:mb-0"
      >
        <span className="text-xl font-black leading-none text-white select-none logo">
          tails
        </span>
      </a>
      <div className="relative flex-col hidden h-full md:flex md:flex-row">
        <nav className="flex flex-wrap items-center h-full pt-3 pb-5 mb-4 text-base border-b border-gray-800 md:pt-0 md:mb-0 md:border-b-0 md:pr-1 md:mr-1 md:border-r md:pb-0">
          <a
            href="#_"
            className="flex items-center h-full px-4 font-medium leading-6 text-gray-200 hover:text-gray-100 hover:bg-gray-800"
          >
            Home
          </a>
          <a
            href="features"
            className="flex items-center h-full px-4 font-medium leading-6 text-gray-200 hover:text-gray-100 hover:bg-gray-800"
          >
            Features
          
          </a>
          <a
            href="pricing"
            className="flex items-center h-full px-4 font-medium leading-6 text-gray-200 hover:text-gray-100 hover:bg-gray-800"
          >
            Pricing
          </a>
          <a
            href="blog"
            className="flex items-center h-full px-4 font-medium leading-6 text-gray-200 hover:text-gray-100 hover:bg-gray-800"
          >
            Blog
          </a>
        </nav>
        <div className="inline-flex items-center justify-center h-full md:justify-end">
          <a
            href="signin"
            className="flex items-center h-full px-5 text-base font-medium leading-6 text-gray-200 whitespace-no-wrap transition duration-150 ease-in-out hover:bg-gray-800 hover:text-gray-100"
          >
            Sign in
          </a>
          <a
            href="signup"
            className="inline-flex items-center justify-center h-full px-4 text-base font-medium leading-6 text-white whitespace-no-wrap transition duration-150 ease-in-out bg-pink-600 border border-transparent hover:bg-pink-500 focus:outline-none focus:border-pink-700 focus:shadow-outline-indigo active:bg-pink-700"
          >
            Sign up
          </a>
        </div>
      </div>
      <div className="absolute top-0 right-0 flex items-center justify-center h-full pr-4 cursor-pointer md:hidden">
        <svg
          className="w-6 h-6 text-gray-100"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M4 8h16M4 16h16"
          />
        </svg>
      </div>
    </div>
  </section>


  
      <section className="relative w-full flex flex-col-reverse px-6 py-16 bg-gray-900 lg:pt-0 lg:flex-col lg:pb-0">
  <div className="inset-y-0 top-0 right-0 z-0 w-full max-w-xl px-4 mx-auto md:px-0 lg:pr-0 lg:mb-0 lg:mx-0 lg:w-7/12 lg:max-w-full lg:absolute xl:px-0">
    <svg
      className="absolute left-0 hidden h-full text-gray-900 transform -translate-x-1/2 lg:block"
      viewBox="0 0 100 100"
      fill="currentColor"
      preserveAspectRatio="none slice"
    >
      <path d="M50 0H80L50 120H0L50 0Z" />
    </svg>
    <img
      className="object-cover w-full h-56 rounded shadow-lg lg:rounded-none lg:shadow-none md:h-96 lg:h-full"
      src="https://images.unsplash.com/photo-1601933470096-0e34634ffcde?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80"
      alt=""
    />
  </div>
  <div className="relative flex min h-screen flex-col items-start w-full max-w-xl px-4 mx-auto md:px-0 lg:px-8 lg:max-w-screen-xl">
    <div className="mb-16 lg:my-40 lg:max-w-lg lg:pr-5">
      <p className="flex inline-block text-sm font-semibold tracking-wider text-purple-200 uppercase rounded-full mb-7">
        New Features
      </p>
      <h1 className="mb-5 font-sans text-3xl font-bold tracking-tight text-white sm:text-6xl sm:leading-none">
        {data.data.attributes.Title}
        
        <span className="inline-block text-purple-500"></span>
      </h1>
      <p className="mb-5 text-base text-gray-300 sm:pr-10 md:text-lg">
        Learn how we are tranforming the world of web design. These
        state-of-the-art innovative tools will remind you of why you got into
        design in the first place.
      </p>
      <div className="flex flex-col items-center pt-2 sm:flex-row sm:pt-4">
        <a
          href="signup"
          className="inline-flex items-center justify-center w-full h-12 px-6 mb-4 font-medium tracking-wide text-white transition duration-200 bg-purple-500 rounded shadow-md sm:w-auto sm:mr-4 sm:mb-0 hover:bg-deep-purple-accent-700 focus:shadow-outline focus:outline-none"
        >
        Get started
        </a>
        <a
          href="/"
          className="inline-flex items-center justify-center w-full h-12 px-6 font-medium tracking-wide text-white transition duration-200 bg-gray-700 rounded shadow-md sm:w-auto hover:bg-deep-purple-accent-700 focus:shadow-outline focus:outline-none"
        >
          Learn More
        </a>
      </div>
    </div>
  </div>

</section>
  <section className="py-20 bg-white">
    <div className="container max-w-6xl mx-auto">
      <h2 className="text-4xl font-bold tracking-tight text-center">
        {data.data.attributes.Description}
      </h2>
      <p className="mt-2 text-lg text-center text-gray-600">
        Check out our list of awesome features below.
      </p>
      <div className="grid grid-cols-4 gap-8 mt-10 sm:grid-cols-8 lg:grid-cols-12 sm:px-8 xl:px-0">
        <div className="relative flex flex-col items-center justify-between col-span-4 px-8 py-12 space-y-4 overflow-hidden bg-gray-100 sm:rounded-xl">
          <div className="p-3 text-white bg-blue-500 rounded-full">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-8 h-8 "
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path d="M14 3v4a1 1 0 0 0 1 1h4" />
              <path d="M5 8v-3a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2h-5" />
              <circle cx={6} cy={14} r={3} />
              <path d="M4.5 17l-1.5 5l3 -1.5l3 1.5l-1.5 -5" />
            </svg>
          </div>
          <h4 className="text-xl font-medium text-gray-700">Certifications</h4>
          <p className="text-base text-center text-gray-500">
            Each of our plan will provide you and your team with certifications.
          </p>
        </div>
        <div className="flex flex-col items-center justify-between col-span-4 px-8 py-12 space-y-4 bg-gray-100 sm:rounded-xl">
          <div className="p-3 text-white bg-blue-500 rounded-full">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-8 h-8 "
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path d="M18 8a3 3 0 0 1 0 6" />
              <path d="M10 8v11a1 1 0 0 1 -1 1h-1a1 1 0 0 1 -1 -1v-5" />
              <path d="M12 8h0l4.524 -3.77a0.9 .9 0 0 1 1.476 .692v12.156a0.9 .9 0 0 1 -1.476 .692l-4.524 -3.77h-8a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h8" />
            </svg>
          </div>
          <h4 className="text-xl font-medium text-gray-700">Notifications</h4>
          <p className="text-base text-center text-gray-500">
            Send out notifications to all your customers to keep them engaged.
          </p>
        </div>
        <div className="flex flex-col items-center justify-between col-span-4 px-8 py-12 space-y-4 bg-gray-100 sm:rounded-xl">
          <div className="p-3 text-white bg-blue-500 rounded-full">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-8 h-8 "
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3" />
              <line x1={12} y1={12} x2={20} y2="7.5" />
              <line x1={12} y1={12} x2={12} y2={21} />
              <line x1={12} y1={12} x2={4} y2="7.5" />
              <line x1={16} y1="5.25" x2={8} y2="9.75" />
            </svg>
          </div>
          <h4 className="text-xl font-medium text-gray-700">Bundles</h4>
          <p className="text-base text-center text-gray-500">
            High-quality bundles of awesome tools to help you out.
          </p>
        </div>
        <div className="flex flex-col items-center justify-between col-span-4 px-8 py-12 space-y-4 bg-gray-100 sm:rounded-xl">
          <div className="p-3 text-white bg-blue-500 rounded-full">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-8 h-8 "
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path d="M8 9l3 3l-3 3" />
              <line x1={13} y1={15} x2={16} y2={15} />
              <rect x={3} y={4} width={18} height={16} rx={2} />
            </svg>
          </div>
          <h4 className="text-xl font-medium text-gray-700">Developer Tools</h4>
          <p className="text-base text-center text-gray-500">
            Developer tools to help grow your application and keep it
            up-to-date.
          </p>
        </div>
        <div className="flex flex-col items-center justify-between col-span-4 px-8 py-12 space-y-4 bg-gray-100 sm:rounded-xl">
          <div className="p-3 text-white bg-blue-500 rounded-full">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-8 h-8 "
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <line x1="9.5" y1={11} x2="9.51" y2={11} />
              <line x1="14.5" y1={11} x2="14.51" y2={11} />
              <path d="M9.5 15a3.5 3.5 0 0 0 5 0" />
              <path d="M7 5h1v-2h8v2h1a3 3 0 0 1 3 3v9a3 3 0 0 1 -3 3v1h-10v-1a3 3 0 0 1 -3 -3v-9a3 3 0 0 1 3 -3" />
            </svg>
          </div>
          <h4 className="text-xl font-medium text-gray-700">Building Blocks</h4>
          <p className="text-base text-center text-gray-500">
            The right kind of building blocks to take your company to the next
            level.
          </p>
        </div>
        <div className="flex flex-col items-center justify-between col-span-4 px-8 py-12 space-y-4 bg-gray-100 sm:rounded-xl">
          <div className="p-3 text-white bg-blue-500 rounded-full">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-8 h-8 "
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <line x1={15} y1={5} x2={15} y2={7} />
              <line x1={15} y1={11} x2={15} y2={13} />
              <line x1={15} y1={17} x2={15} y2={19} />
              <path d="M5 5h14a2 2 0 0 1 2 2v3a2 2 0 0 0 0 4v3a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-3a2 2 0 0 0 0 -4v-3a2 2 0 0 1 2 -2" />
            </svg>
          </div>
          <h4 className="text-xl font-medium text-gray-700">Coupons</h4>
          <p className="text-base text-center text-gray-500">
            Coupons system to provide special offers and discounts for your app.
          </p>
        </div>
      </div>
    </div>
  </section>
  <section className="box-border py-8 leading-7 text-gray-900 bg-white border-0 border-gray-200 border-solid sm:py-12 md:py-16 lg:py-24">
    <div className="box-border max-w-6xl px-4 pb-12 mx-auto border-solid sm:px-6 md:px-6 lg:px-4">
      <div className="flex flex-col w-full items-center leading-7 text-center text-gray-900">
        <h2 className="box-border m-0 text-3xl font-semibold leading-tight tracking-tight text-black border-solid sm:text-4xl md:text-5xl">
          Pricing Options
        </h2>
        <p className="box-border mt-4 text-2xl leading-normal text-gray-900 border-solid">
          We've got a plan for companies of any size
        </p>
      </div>
      <div className="grid max-w-md mx-auto mt-6 overflow-hidden leading-7 text-gray-900 border border-b-4 border-gray-300 border-blue-600 rounded-xl md:max-w-lg lg:max-w-none sm:mt-10 lg:grid-cols-3">
        <div className="box-border px-4 py-8 mb-6 text-center bg-white border-solid lg:mb-0 sm:px-4 sm:py-8 md:px-8 md:py-12 lg:px-10">
          <h3 className="m-0 text-2xl font-semibold leading-tight tracking-tight text-black border-0 border-solid sm:text-3xl md:text-4xl">
            Basic
          </h3>
          <p className="mt-3 leading-7 text-gray-900 border-0 border-solid">
            The basic plan is a good fit for smaller teams and startups
          </p>
          <div className="flex items-center justify-center mt-6 leading-7 text-gray-900 border-0 border-solid sm:mt-8">
            <p className="box-border m-0 text-6xl font-semibold leading-normal text-center border-0 border-gray-200">
              $19
            </p>
            <p className="box-border my-0 ml-4 mr-0 text-xs text-left border-0 border-gray-200">
              per user <span className="block">per month</span>
            </p>
          </div>
          <button className="inline-flex items-center justify-center w-full py-3 mt-6 font-sans text-sm leading-none text-center text-blue-600 no-underline bg-transparent border border-b-2 border-blue-600 rounded-md cursor-pointer hover:bg-blue-600 hover:border-blue-600 hover:text-white sm:text-base sm:mt-8 md:text-lg">
            Select Plan
          </button>
        </div>
        <div className="box-border px-4 py-8 mb-6 text-center bg-gray-100 border border-gray-300 border-solid lg:mb-0 sm:px-4 sm:py-8 md:px-8 md:py-12 lg:px-10">
          <h3 className="m-0 text-2xl font-semibold leading-tight tracking-tight text-black border-0 border-solid sm:text-3xl md:text-4xl">
            Plus
          </h3>
          <p className="mt-3 leading-7 text-gray-900 border-0 border-solid">
            The plus plan is a good fit for medium-size to larger companies
          </p>
          <div className="flex items-center justify-center mt-6 leading-7 text-gray-900 border-0 border-solid sm:mt-8">
            <p className="box-border m-0 text-6xl font-semibold leading-normal text-center border-0 border-gray-200">
              $39
            </p>
            <p className="box-border my-0 ml-4 mr-0 text-xs text-left border-0 border-gray-200">
              per user <span className="block">per month</span>
            </p>
          </div>
          <button className="inline-flex items-center justify-center w-full py-3 mt-6 font-sans text-sm leading-none text-center text-white no-underline bg-blue-600 border-b-4 border-blue-700 rounded cursor-pointer hover:text-white sm:text-base sm:mt-8 md:text-lg">
            Select Plan
          </button>
        </div>
        <div className="box-border px-4 py-8 text-center bg-white border-solid sm:px-4 sm:py-8 md:px-8 md:py-12 lg:px-10">
          <h3 className="m-0 text-2xl font-semibold leading-tight tracking-tight text-black border-0 border-solid sm:text-3xl md:text-4xl">
            Pro
          </h3>
          <p className="mt-3 leading-7 text-gray-900 border-0 border-solid">
            The pro plan is a good fit for larger and enterprise companies.
          </p>
          <div className="flex items-center justify-center mt-6 leading-7 text-gray-900 border-0 border-solid sm:mt-8">
            <p className="box-border m-0 text-6xl font-semibold leading-normal text-center border-0 border-gray-200">
              $59
            </p>
            <p className="box-border my-0 ml-4 mr-0 text-xs text-center border-0 border-gray-200">
              per user <span className="block">per month</span>
            </p>
          </div>
          <button className="inline-flex items-center justify-center w-full py-3 mt-6 font-sans text-sm leading-none text-center text-blue-600 no-underline bg-transparent border border-b-2 border-blue-600 rounded cursor-pointer hover:bg-blue-600 hover:border-blue-600 hover:text-white sm:text-base sm:mt-8 md:text-lg">
            Select Plan
          </button>
        </div>
      </div>
    </div>
  </section>

      <footer className={styles.footer}>
      <section className="flex flex-col w-full bg-blue-600">
  <div className="px-8 py-12 mx-auto max-w-7xl">
    <div className="grid grid-cols-2 gap-10 mb-3 md:grid-cols-3 lg:grid-cols-12 lg:gap-20">
      <div className="col-span-3">
        <a
          href="#_"
          className="text-xl font-black leading-none text-white select-none logo"
        >
          tails.
        </a>
        <p className="my-4 text-xs leading-normal text-blue-100">
          Beautifully hand-crafted components to help you build amazing pages.
        </p>
      </div>
      <nav className="col-span-1 md:col-span-1 lg:col-span-2">
        <p className="mb-3 text-xs font-semibold tracking-wider text-blue-200 uppercase">
          Product
        </p>
        <a
          href="features"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Features
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Integrations
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Documentation
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          FAQs
        </a>
        <a
          href="pricing"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Pricing
        </a>
      </nav>
    
      <nav className="col-span-1 md:col-span-1 lg:col-span-2">
        <p className="mb-3 text-xs font-semibold tracking-wider text-blue-200 uppercase">
          About
        </p>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Our Story
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Company
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Privacy
        </a>
        <a
          href="blog"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Blog
        </a>
      </nav>
      <nav className="col-span-2 md:col-span-1 lg:col-span-2">
        <p className="mb-3 text-xs font-semibold tracking-wider text-blue-200 uppercase">
          Contact
        </p>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Advertising
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Press
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Email
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Partners
        </a>
        <a
          href="#"
          className="flex mb-3 text-sm font-medium text-blue-100 transition md:mb-2 hover:text-white"
        >
          Jobs
        </a>
      </nav>
      <div className="col-span-3">
        <span className="inline-flex justify-center w-full mt-4 space-x-5 sm:ml-auto sm:mt-0 sm:justify-end">
          <a href="#" className="text-blue-100 hover:text-white">
            <span className="sr-only">Facebook</span>
            <svg
              className="w-6 h-6"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                fillRule="evenodd"
                d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                clipRule="evenodd"
              />
            </svg>
          </a>
          <a href="#" className="text-blue-100 hover:text-white">
            <span className="sr-only">Instagram</span>
            <svg
              className="w-6 h-6"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                fillRule="evenodd"
                d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
                clipRule="evenodd"
              />
            </svg>
          </a>
          <a href="#" className="text-blue-100 hover:text-white">
            <span className="sr-only">Twitter</span>
            <svg
              className="w-6 h-6"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
            </svg>
          </a>
          <a href="#" className="text-blue-100 hover:text-white">
            <span className="sr-only">GitHub</span>
            <svg
              className="w-6 h-6"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                fillRule="evenodd"
                d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                clipRule="evenodd"
              />
            </svg>
          </a>
          <a href="#" className="text-blue-100 hover:text-white">
            <span className="sr-only">Dribbble</span>
            <svg
              className="w-6 h-6"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                fillRule="evenodd"
                d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z"
                clipRule="evenodd"
              />
            </svg>
          </a>
        </span>
      </div>
    </div>
    <div className="flex flex-col items-start justify-between pt-10 mt-10 border-t border-blue-500 md:flex-row md:items-center">
      <p className="mb-6 text-sm text-left text-blue-200 md:mb-0">
        © Copyright 2021 Tails. All Rights Reserved.
      </p>
      <div className="flex items-start justify-start space-x-6 md:items-center md:justify-center">
        <a
          href="#_"
          className="text-sm text-blue-200 transition hover:text-white"
        >
          Terms
        </a>
        <a
          href="#_"
          className="text-sm text-blue-200 transition hover:text-white"
        >
          Privacy
        </a>
      </div>
    </div>
  </div>
</section>

      </footer>
    </div>
  )
}
export async function getStaticProps(){
  const res = await fetch("http://localhost:1337/api/index");
  const getstarted=await res.json();
  const data=getstarted.data
  console.log(data);
  return{
    props:{data},

    

    // const res= await fetch("http://localhost:1337/api/feature");
    // const getstarted=await res.json();
    // const data,feature=getstarted.data
    // console.log(data);
    // return{
    //   props:{data,feature},
      
    
  }
  }
  // export default Index;
